spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://mysql-top:3306/spring_top?autoReconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username : user
    password : password
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        dialect : org.hibernate.dialect.MySQL5Dialect
        ddl-auto : validate
  flyway:
    enabled: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace